<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Admin')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink()->prependStylesheet('//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
            ->prependFile('//netdna.bootstrapcdn.com/bootstrap/2.1.1/js/bootstrap.min.js')
            ->prependFile('//code.jquery.com/jquery-migrate-1.2.1.min.js')
            ->prependFile('//code.jquery.com/jquery-1.11.0.min.js')
            ->prependFile(
                '//html5shiv.googlecode.com/svn/trunk/html5.js', 
                'text/javascript', 
                array('conditional' => 'lt IE 9',)
        ) ?>
  </head>
  <body>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('zfcadmin') ?>">Admin</a>
          <div class="nav-collapse">
            <?php 
            if($this->zfcUserIdentity())
            {
                echo $this->navigation('admin_navigation')
                            ->menu()
                            ->setUlClass('nav')
                            ->setMaxDepth(0)
                            ->setRenderInvisible(false);
            }
            ?>
          </div><!--/.nav-collapse -->
          <div style="float: right">
            <?php
            if($this->zfcUserIdentity())
            {
                echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array("img_size" => 20 )) 
                ?>
                <h5 style="display: inline-block;"> 
                    Hello, <?php echo $this->zfcUserDisplayName() ?>!
                </h5> 
                <a href="<?php echo $this->url('zfcuser') ?>" title="Settings">
                    <i class="icon-cog"></i>
                </a>
                <a href="<?php echo $this->url('zfcuser/logout') ?>" title="Sign Out">
                    <i class="icon-signout"></i>
                </a>
            <?php
            }
            ?>
        </div>
        </div>
      </div>
    </div>
    <div class="container">
        <div>
            <?php echo $this->flashMessenger()->render("success", array('alert', 'alert-success' , 'unstyled'));?>
            <?php echo $this->flashMessenger()->render("error", array('alert', 'alert-error' , 'unstyled'));?>
        </div>
      <?php echo $this->content; ?>
      <hr>
      <footer>
        <p>&copy; <?php echo date("Y");?> by Icor Orphans. All rights reserved.</p>
      </footer>
    </div> <!-- /container -->
    <?php echo $this->inlineScript() ?>
  </body>
</html>
