
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>WdgAdmin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Le styles -->
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css" media="screen" rel="stylesheet" type="text/css">
    <!-- Scripts -->
    <!--[if lt IE 9]><script type="text/javascript" src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <script type="text/javascript" src="//code.jquery.com/jquery.min.js"></script>
    <script type="text/javascript" src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js"></script>
</head>

<body>

<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/admin">WdgAdmin</a>
            <div class="nav-collapse">
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container">

    <?php echo $this->content ?>

    <hr>
    <footer>
        <p>&copy; <?php echo date('Y') ?> by <a href="http://www.webdevgods.com/">Web Dev Gods</a>, All rights reserved.</p>
    </footer>

</div> <!-- /container -->

</body>
</html>
